#!/bin/busybox sh

# Mount the /proc and /sys filesystems.
mount -t proc none /proc
mount -t sysfs none /sys

#exec switch_root / /bin/sh
#switch_root [-c /dev/console] NEW_ROOT NEW_INIT [ARGS]

/bin/sh
